version: '3.6'

secrets:
  project_registration_token_v1:
    external: true

services:
  runner:
    image: dreampathsprojekt/gitlab-runner-swarm:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/elk/logstash/pipeline:/opt
    secrets:
    - source: project_registration_token_v1
      target: project_registration_token
    environment:
      GITLAB_URL: "https://gitlab.com/"
      DOCKER_VOLUME_1: /var/run/docker.sock:/var/run/docker.sock
      DOCKER_VOLUME_2: /tmp/elk/logstash/pipeline:/opt
      RUNNER_DESCRIPTION: "custom-docker-runner"
    deploy:
      replicas: 3